### ISSUE TITLE
HyperExpress Plugin Errors on Test

### ISSUE THREAD

**Issue by tfredrich** [RestExpress/HyperExpress#16]
On a previous project we used Spock to test our RestExpress end points.  Each test suite (spec really) would create an instance of the RestExpress object and then send HTTP requests to RestExpress.  When the test suite was done, we'd shut down that server.  That worked well.  

In our current project we're using the HyperExpressPlugin and our practice of creating multiple RestExpress objects in one JVM (one after the other) is causing problems:
com.strategicgains.hyperexpress.exception.ResourceException: Duplicate content type: application/json; charset=UTF-8

        at com.strategicgains.hyperexpress.DefaultResourceFactory.addFactoryStrategy(DefaultResourceFactory.java:75)
        at com.strategicgains.hyperexpress.HyperExpress._registerResourceFactoryStrategy(HyperExpress.java:252)
        at com.strategicgains.hyperexpress.HyperExpress.registerResourceFactoryStrategy(HyperExpress.java:118)
        at org.restexpress.plugin.hyperexpress.HyperExpressPlugin.bind(HyperExpressPlugin.java:108)
        at org.restexpress.RestExpress.bindPlugins(RestExpress.java:787)
        at org.restexpress.RestExpress.bind(RestExpress.java:627)
        at org.restexpress.RestExpress.bind(RestExpress.java:570)
        at com.pearson.gambit.magni.server.Server.bindToPort(Server.java:108)
        at com.pearson.gambit.magni.server.Server.start(Server.java:91)
        at com.pearson.gambit.magni.evidence.EvidenceControllerSpec.setupSpec(EvidenceControllerSpec.groovy:31)

**Comment by tfredrich** [comment]
As of version 2.6-SNAPSHOT call HyperExpress.reset() to re-initialise HyperExpress when starting up a new server.
