### ISSUE TITLE
HyperExpress.createCollectionResource() does not support generic collections

### ISSUE THREAD

**Issue by Alexander-Yarko** [RestExpress/HyperExpress#6]
Hi Todd.
Could you please have a look at the method HyperExpress.createCollectionResource() ?
Seems like the generic collections are not supported.
the following exception is reproduced:

```
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
    at com.strategicgains.hyperexpress.builder.TokenResolver.callTokenBinders(TokenResolver.java:221)
    at com.strategicgains.hyperexpress.builder.TokenResolver.resolve(TokenResolver.java:158)
    at com.strategicgains.hyperexpress.builder.UrlBuilder.build(UrlBuilder.java:249)
    at com.strategicgains.hyperexpress.builder.UrlBuilder.build(UrlBuilder.java:218)
    at com.strategicgains.hyperexpress.builder.LinkBuilder.build(LinkBuilder.java:265)
    at com.strategicgains.hyperexpress.builder.ConditionalLinkBuilder.build(ConditionalLinkBuilder.java:128)
    at com.strategicgains.hyperexpress.HyperExpress._resolveUrlTokens(HyperExpress.java:374)
    at com.strategicgains.hyperexpress.HyperExpress._assignResourceLinks(HyperExpress.java:391)
    at com.strategicgains.hyperexpress.HyperExpress._createResource(HyperExpress.java:249)
    at com.strategicgains.hyperexpress.HyperExpress._createCollectionResource(HyperExpress.java:319)
    at com.strategicgains.hyperexpress.HyperExpress.createCollectionResource(HyperExpress.java:160)
    at com.aayarko.med.webservice.controller.AbstractController.readAll(AbstractController.java:79)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
```

Appropriate code is very simple:

```
final List<T> entities = getService().readAll(filter, range, order);
final Resource resource = HyperExpress.createCollectionResource(entities, getType(), "application/hal+json");
```

But the following code w/o generics works perfect:

```
final List<Case> entities = caseService.readAll(filter, range, order);
final Resource resource = HyperExpress.createCollectionResource(entities, getType(), "application/hal+json");
```

Thank you.

**Comment by tfredrich** [comment]
Hi @Alexander-Yarko,

Thanks again for your issue post.  In creating a unit test to replicate your results, I'm wondering what the implementation for the getType() method so I can replicate it. Unfortunately, I have been unable to replicate.

Here's my test:

	@Test
	public void shouldCreateGenericCollection()
	{
		List<?> entities = getEntities();
		Resource resource = HyperExpress.createCollectionResource(entities, getType(), "application/hal+json");
	}

	private List<?> getEntities()
	{
		return new ArrayList<Blog>();
	}

	private Class<?> getType()
	{
		return Blog.class;
	}

Obviously, I'm not replicating your conditions. Help is welcomed.

Thanks,
--Todd
