### ISSUE TITLE
[HAL] Error at link array deserialization.

### ISSUE THREAD

**Issue by zab-align** [RestExpress/HyperExpress#9]
Hello.

We have source file in HAL format:

```
{
	"SessionId":"9d1b29fc-4240-4993-82c5-a42d00900324",
	"_links":{
		"self":{"href":"/api/orders/9d1b29fc-4240-4993-82c5-a42d00900324/scandata"},
		"orderstate":[	{"href":"/api/orders/9d1b29fc-4240-4993-82c5-a42d00900324/orderstate?orderState=Accepted","title":"Accept"},
						{"href":"/api/orders/9d1b29fc-4240-4993-82c5-a42d00900324/orderstate?orderState=Declined","title":"Decline"} ]
	}
}
```

Then we trying to deserialize it to get links with this snippet of code:

```
ObjectMapper mapper = new ObjectMapper();
SimpleModule module = new SimpleModule();
module.addDeserializer(HalResource.class, new HalResourceDeserializer());
mapper.registerModule(module);
HalResource halResource = mapper.readValue(response.getBody(), HalResource.class);
```

As the result the exception is raised:

```
java.lang.IllegalStateException: Null URL pattern
	at com.strategicgains.hyperexpress.builder.UrlBuilder.buildFullUrlPattern(UrlBuilder.java:256)
	at com.strategicgains.hyperexpress.builder.UrlBuilder.build(UrlBuilder.java:204)
	at com.strategicgains.hyperexpress.builder.LinkBuilder.build(LinkBuilder.java:252)
	at com.strategicgains.hyperexpress.builder.LinkBuilder.build(LinkBuilder.java:247)
	at com.strategicgains.hyperexpress.serialization.jackson.HalResourceDeserializer.addAllLinks(HalResourceDeserializer.java:142)
	at com.strategicgains.hyperexpress.serialization.jackson.HalResourceDeserializer.processLinks(HalResourceDeserializer.java:90)
	at com.strategicgains.hyperexpress.serialization.jackson.HalResourceDeserializer.deserializeResource(HalResourceDeserializer.java:61)
	at com.strategicgains.hyperexpress.serialization.jackson.HalResourceDeserializer.deserialize(HalResourceDeserializer.java:54)
	at com.strategicgains.hyperexpress.serialization.jackson.HalResourceDeserializer.deserialize(HalResourceDeserializer.java:40)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2192)
```

In case if array of links ('orderstate') removed everything is deserialized without problems.

**Comment by tfredrich** [comment]
Thank you for the detailed report. I was able to fix it. Now in 0.3.0-SNAPSHOT (which will require RestExpress 0.11.0-SNAPSHOT if you're using the RestExpressPlugin). Let me know if you need me to back-port it to 2.2.
